# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2020-05-16 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20200516_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'verbose_name': '\u7528\u6237\u7559\u8a00\u4fe1\u606f', 'verbose_name_plural': '\u7528\u6237\u7559\u8a00\u4fe1\u606f'},
        ),
    ]
